#!/bin/bash
# This script is auto-generated by main.py
set -e  # Exit immediately on error
set -x  # Print commands as they execute

# 1. Clean and create target directories
echo 'Cleaning codebases directory...'
rm -rf '/Users/luketych/Dev/_libraries/quartz/viscera/content/codebases'
mkdir -p '/Users/luketych/Dev/_libraries/quartz/viscera/content/codebases'

echo 'Cleaning descriptions directory...'
rm -rf '/Users/luketych/Dev/_libraries/quartz/viscera/content/descriptions'
mkdir -p '/Users/luketych/Dev/_libraries/quartz/viscera/content/descriptions'

echo 'Cleaning visceras directory...'
rm -rf '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras'
mkdir -p '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras'

# 2. Copy content from source codebases
echo 'Processing _util/_util_with_mcp'
mkdir -p '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras/_util'
cp -R '/Users/luketych/Dev/_util/_util_with_mcp/viscera' '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras/_util/_util_with_mcp'
cp -R '/Users/luketych/Dev/_util/_util_with_mcp' '/Users/luketych/Dev/_libraries/quartz/viscera/content/codebases/_util--_util_with_mcp'

echo 'Processing _util/profiler'
mkdir -p '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras/_util'
cp -R '/Users/luketych/Dev/_util/profiler/viscera' '/Users/luketych/Dev/_libraries/quartz/viscera/content/visceras/_util/profiler'
cp -R '/Users/luketych/Dev/_util/profiler' '/Users/luketych/Dev/_libraries/quartz/viscera/content/codebases/_util--profiler'

echo '--- Content Aggregation Complete ---
'