import argparse
import subprocess
from pathlib import Path
from datetime import datetime

from config import get_config
from find_codebases import find_codebases
from utils.sanitize_path_to_name import sanitize_path_to_name

def generate_script(codebase_paths: list[Path], quartz_content_dir: Path, content_types: list[str]) -> str:
    """Generates the final, executable shell script content based on the configured content types."""
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    backup_dir = quartz_content_dir.parent / f"{quartz_content_dir.name}.bak-{timestamp}"

    commands = ["#!/bin/bash", "# This script is auto-generated by main.py", "set -e", "set -x", ""]

    # 1. Backup old content and create fresh directories
    commands.append("# 1. Backup old content and create fresh directories")
    commands.append(f"echo 'Backing up existing content directory to {backup_dir}...'" )
    commands.append(f"if [ -d '{quartz_content_dir}' ]; then mv '{quartz_content_dir}' '{backup_dir}'; fi")
    # Create directories for each configured content type
    for content_type in content_types:
        commands.append(f"mkdir -p '{quartz_content_dir / content_type}'")
    commands.append("")

    # 2. Copy content from source codebases
    commands.append("# 2. Copy content from source codebases")
    for codebase_path in codebase_paths:
        sanitized_name = sanitize_path_to_name(codebase_path)
        commands.append(f"echo 'Processing {codebase_path}'")

        # Copy each configured content type into its central directory
        for content_type in content_types:
            source_path = codebase_path / content_type
            dest_path = quartz_content_dir / content_type / sanitized_name
            # Check if the source directory exists before copying
            commands.append(f"if [ -d '{source_path}' ]; then cp -R '{source_path}' '{dest_path}'; fi")

        commands.append("") # Add a newline for readability

    commands.append("echo '--- Content Aggregation Complete ---'")
    return "\n".join(commands)

def main():
    parser = argparse.ArgumentParser(description="Generate a script to aggregate content for Quartz.")
    parser.add_argument(
        '--execute',
        action='store_true',
        help="Generate and execute the final script without interactive confirmation. Use with caution."
    )
    parser.add_argument(
        '-y', '--yes',
        action='store_true',
        help="Automatically approve the plan without interactive confirmation."
    )
    parser.add_argument(
        '--env',
        type=str,
        default='prod',
        help="The environment to run in (prod or test)."
    )
    args = parser.parse_args()

    _, quartz_content_dir, content_types = get_config(env=args.env)
    codebase_paths = find_codebases(env=args.env)
    num_codebases = len(codebase_paths)

    # --- Phase 1: Dry Run and Verification ---
    if not args.execute:
        print("--- Dry Run Plan ---")
        print(f"\nFound {num_codebases} valid codebases to process based on the presence of: {', '.join(content_types)}.")
        print("\nActions to be performed:")
        
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        backup_dir_name = f"{quartz_content_dir.name}.bak-{timestamp}"
        print(f"1.  BACKUP: The existing '{quartz_content_dir}' directory will be moved to a backup location like '{quartz_content_dir.parent / backup_dir_name}'.")
        
        # Create a list of directories to be created
        dirs_to_create = content_types
        print(f"2.  CREATE: {len(dirs_to_create)} new directories will be created: {', '.join(dirs_to_create)}.")

        print(f"3.  COPY: The '{', '.join(content_types)}' from {num_codebases} projects will be copied.")
        
        # Display the copy plan for each codebase and content type
        for src_path in codebase_paths[:5]: # Limit preview to first 5
            for content_type in content_types:
                sanitized_name = sanitize_path_to_name(src_path)
                dest_path = quartz_content_dir / content_type / sanitized_name
                print(f"    - {src_path / content_type} -> {dest_path}")
        
        if num_codebases > 5:
            print(f"    ...and {num_codebases - 5} more.")

        print("\nNo files will be changed by this dry run.")
        
        if not args.yes:
            try:
                confirm = input("\nDo you want to generate the final shell script to execute this plan? (y/n): ")
            except KeyboardInterrupt:
                print("\n\nOperation cancelled by user.")
                return

            if confirm.lower() != 'y':
                print("Operation cancelled. No script will be generated.")
                return
        
        print("\n✅ Plan approved. Generating final script...")

    # --- Phase 2 & 3: Script Generation and Final Output ---
    script_content = generate_script(codebase_paths, quartz_content_dir, content_types)
    
    script_file = Path("aggregator_script.sh")
    script_file.write_text(script_content)
    script_file.chmod(0o755) # Make it executable

    print(f"\n✅ Final script '{script_file}' has been generated.")

    if args.execute:
        print("\n🚀 Executing script...")
        subprocess.run(["./" + str(script_file)], check=True)
        print("\n✅ Script executed successfully.")
        # Optional: Clean up the script file after execution
        # script_file.unlink()
    else:
        print("You can now review and execute it.")

if __name__ == "__main__":
    main()
