import argparse
import subprocess
from pathlib import Path
from datetime import datetime

from config import get_config
from find_codebases import find_codebases
from utils.sanitize_path_to_name import sanitize_path_to_name

def generate_script(codebase_paths: list[Path], quartz_content_dir: Path) -> str:
    """Generates the final, executable shell script content."""
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    backup_dir = quartz_content_dir.parent / f"{quartz_content_dir.name}.bak-{timestamp}"

    commands = ["#!/bin/bash", "# This script is auto-generated by main.py", "set -e", "set -x", ""]

    # 1. Backup old content and create fresh directories
    commands.append("# 1. Backup old content and create fresh directories")
    commands.append(f"echo 'Backing up existing content directory to {backup_dir}...'" )
    commands.append(f"if [ -d '{quartz_content_dir}' ]; then mv '{quartz_content_dir}' '{backup_dir}'; fi")
    commands.append(f"mkdir -p '{quartz_content_dir / 'codebases'}'")
    commands.append(f"mkdir -p '{quartz_content_dir / 'descriptions'}'")
    commands.append(f"mkdir -p '{quartz_content_dir / 'visceras'}'")
    commands.append("")

    # 2. Copy content from source codebases
    commands.append("# 2. Copy content from source codebases")
    for codebase_path in codebase_paths:
        sanitized_name = sanitize_path_to_name(codebase_path)
        commands.append(f"echo 'Processing {codebase_path}'")

        # Define source paths
        source_desc_path = codebase_path / 'descriptions'
        source_visc_path = codebase_path / 'viscera'

        # Define destination paths
        dest_codebase_path = quartz_content_dir / 'codebases' / sanitized_name
        dest_desc_path = quartz_content_dir / 'descriptions' / sanitized_name
        dest_visc_path = quartz_content_dir / 'visceras' / sanitized_name

        # A. Copy the full codebase into the 'codebases' directory
        commands.append(f"cp -R '{codebase_path}' '{dest_codebase_path}'")

        # B. Copy the 'descriptions' folder into the central 'descriptions' directory
        commands.append(f"cp -R '{source_desc_path}' '{dest_desc_path}'")

        # C. Copy the 'viscera' folder into the central 'visceras' directory
        commands.append(f"cp -R '{source_visc_path}' '{dest_visc_path}'")
        commands.append("") # Add a newline for readability

    commands.append("echo '--- Content Aggregation Complete ---'")
    return "\n".join(commands)

def main():
    parser = argparse.ArgumentParser(description="Generate a script to aggregate content for Quartz.")
    parser.add_argument(
        '--execute',
        action='store_true',
        help="Generate and execute the final script without interactive confirmation. Use with caution."
    )
    parser.add_argument(
        '-y', '--yes',
        action='store_true',
        help="Automatically approve the plan without interactive confirmation."
    )
    args = parser.parse_args()

    _, quartz_content_dir = get_config()
    codebase_paths = find_codebases()
    num_codebases = len(codebase_paths)

    # --- Phase 1: Dry Run and Verification ---
    if not args.execute:
        print("--- Dry Run Plan ---")
        print(f"\nFound {num_codebases} valid codebases to process.")
        print("\nActions to be performed:")
        
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        backup_dir_name = f"{quartz_content_dir.name}.bak-{timestamp}"
        print(f"1.  BACKUP: The existing '{quartz_content_dir}' directory will be moved to a backup location like '{quartz_content_dir.parent / backup_dir_name}'.")
        print("2.  CREATE: 3 new directories will be created: 'codebases', 'descriptions', 'visceras'.")
        print(f"3.  COPY: {num_codebases} projects will be copied.")
        
        for path in codebase_paths[:5]:
             sanitized_name = sanitize_path_to_name(path)
             print(f"    - {path} -> {quartz_content_dir / 'codebases' / sanitized_name}")
        if num_codebases > 5:
            print(f"    ...and {num_codebases - 5} more.")

        print("\nNo files will be changed by this dry run.")
        
        if not args.yes:
            try:
                confirm = input("\nDo you want to generate the final shell script to execute this plan? (y/n): ")
            except KeyboardInterrupt:
                print("\n\nOperation cancelled by user.")
                return

            if confirm.lower() != 'y':
                print("Operation cancelled. No script will be generated.")
                return
        
        print("\n✅ Plan approved. Generating final script...")

    # --- Phase 2 & 3: Script Generation and Final Output ---
    script_content = generate_script(codebase_paths, quartz_content_dir)
    
    script_file = Path("aggregator_script.sh")
    script_file.write_text(script_content)
    script_file.chmod(0o755) # Make it executable

    print(f"\n✅ Final script '{script_file}' has been generated.")

    if args.execute:
        print("\n🚀 Executing script...")
        subprocess.run(["./" + str(script_file)], check=True)
        print("\n✅ Script executed successfully.")
        # Optional: Clean up the script file after execution
        # script_file.unlink()
    else:
        print("You can now review and execute it.")

if __name__ == "__main__":
    main()
