name: Build and Deploy to Organization Repos

on:
  push:
    branches:
      - feature-unique_urls
  workflow_dispatch:

jobs:
  list-sites:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          sites=$(ls -d viscera/content/*/ | xargs -n 1 basename)
          echo "matrix={\"site\":$(echo $sites | jq -R 'split(\" \")' | jq -c 'map(select(length > 0))')}" >> $GITHUB_OUTPUT

  deploy:
    needs: list-sites
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.list-sites.outputs.matrix) }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        working-directory: ./viscera

      - name: Build Site - ${{ matrix.site }}
        run: npx quartz build --directory "viscera/content/${{ matrix.site }}"

      - name: Deploy to luke-quartz/${{ matrix.site }}
        uses: peaceiris/actions-gh-pages@v4
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the directory that contains all the built sites
          path: ./all-sites

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
